apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: testing-some-multi-k8s.pw
  dnsNames:
    - testing-some-multi-k8s.pw
    - www.testing-some-multi-k8s.pw
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - testing-some-multi-k8s.pw
          - www.testing-some-multi-k8s.pw
